<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.41" />


<title>Adding Observations in RLMS using R - Privalko Blog</title>
<meta property="og:title" content="Adding Observations in RLMS using R - Privalko Blog">



  








<link href='//cdn.bootcss.com/highlight.js/9.11.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">

<script src="https://use.fontawesome.com/dc8f5495c2.js"></script>


  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/tupac.jpg"
         width="50"
         height="50"
         alt="Logo">
  </a>
  <ul class="nav-links">
    
    <li><a href="/about/"><i class="fa fa-bullhorn fa-lg fa-fw" aria-hidden="true"></i>&nbsp; About</a></li>
    
    <li><a href="https://www.linkedin.com/in/ivan-privalko-8a790743/"><i class="fa fa-linkedin fa-lg fa-fw" aria-hidden="true"></i>&nbsp; LinkedIn</a></li>
    
    <li><a href="https://twitter.com/privlko"><i class="fa fa-twitter fa-lg fa-fw" aria-hidden="true"></i>&nbsp; Twitter</a></li>
    
  </ul>
</nav>
      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">10 min read</span>
    

    <h1 class="article-title">Adding Observations in RLMS using R</h1>

    
    <span class="article-date">2018/06/03</span>
    

    <div class="article-content">
      <p>In this update, I want to update the blog with a practical post. I’ll try to group observations in the <a href="http://www.cpc.unc.edu/projects/rlms-hse">Russian Longitudinal Monitoring Survey</a> by individual. In a nutshell, every year, the survey asks people a series of questions, but some respondents are revisited and asked the same questions at another point in time. This is the basis for longitudinal data.</p>
<p>I should add a disclaimer, I have a limited knowledge of the Russia Longitudinal Monitoring Survey, and it’s possible that other, better methods exist. For the moment, I am trying to understand some of R’s methods for putting together panel observations for individuals. In Stata, you can group observations by individuals using the command “append”. What does this look like in R?</p>
<div id="loading-the-data" class="section level1">
<h1>Loading the data</h1>
<p>In this example, I’ll group two years of observations, RLMS’s 2015 survey with the 2014 survey. I’m using the <a href="https://www.tidyverse.org">tidyverse package</a>, and the instructions from Hadley Wickham’s <a href="http://r4ds.had.co.nz">R for Data Science</a>. Firstly, I dowload the survey years from the RLMS website, in R format. No need to take the Stata version and convert it to R. Both years are now sitting in my desktop. I begin by loading the data for 2015.</p>
<pre class="r"><code>load(&quot;C:/Users/Ivan/Desktop/dir/data/rlms/adult2015x.RData&quot;)
y2015 &lt;- x %&gt;%
  select(round, 
         id = tid,
         gndr = ixgender,
         income = ixinclmo)</code></pre>
<p>The <strong>load</strong> command saves the entire file to a variable called x. I’m not interested in using the whole file, so I use some commands from <a href="https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html">dplyr</a> to pick out the measures I need. RLMS contains some arbitrary prefixes for variables, which I also edit out. The most important variable in the set is the id, which I’ll use as a “key” for matching measures in both years to the same individuals.</p>
<p>Before moving on, it’s worth checking if the file was uploaded correctly.</p>
<pre class="r"><code>as.tibble(y2015)</code></pre>
<pre><code>## # A tibble: 15,118 x 4
##    round      id  gndr income
##  * &lt;int&gt;   &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
##  1    24 1000101     2  40000
##  2    24 1000203     2  47000
##  3    24 1000301     2  14514
##  4    24 1000401     2  13400
##  5    24 1001001     2  22000
##  6    24 1001102     2  36350
##  7    24 1001201     2  44000
##  8    24 1001301     1  28000
##  9    24 1001302     2  24500
## 10    24 1001401     2  15300
## # ... with 15,108 more rows</code></pre>
<p>The first column, running from 1 to 10 lists the observations. The vector <em>round</em>, notes that all observations are from the 24th round of data collection (back in 2015). The <em>id</em> variable capture’s a respondents unique identifier. The last two measures capture their gender, and their age. Since gender is a factor, we can recode this, but I will leave this for another update. For now, I have the data for 2015 loaded, and it seems to have about 15,000+ observations with measures of gender and income. I now consider the data for 2014.</p>
<pre class="r"><code>load(&quot;C:/Users/Ivan/Desktop/dir/data/rlms/adult2014w.RData&quot;)
y2014 &lt;- x %&gt;%
  select(round, 
         id = sid,
         gndr = iwgender,
         income = iwinclmo)</code></pre>
<p>The code above is slightly different to the previous year’s. The variables which capture gender, income and ID are different from the previous dataset, and have a different set of prefixes. I delete these and give the variables names that are similar to the previous dataset. Again, I only use a subset of measures here, to keep things simple. The data from 2014 looks like this.</p>
<pre class="r"><code>as.tibble(y2014)</code></pre>
<pre><code>## # A tibble: 15,173 x 4
##    round      id  gndr income
##  * &lt;int&gt;   &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
##  1    23 1000101     2  36000
##  2    23 1000103     1   7240
##  3    23 1000203     2  70000
##  4    23 1000301     2  13180
##  5    23 1000401     2  12200
##  6    23 1001001     2  18500
##  7    23 1001102     2  25000
##  8    23 1001201     2  45800
##  9    23 1001301     1  35000
## 10    23 1001302     2   9300
## # ... with 15,163 more rows</code></pre>
<p>Again, the numbers running 1 to 10 are observations. The number for <strong>round</strong> has changed, since we are now dealing with round 23 (the data from 2014). The ID’s are somewhat similar than in 2015. The person 1000101 seems to answer some questions in both 2015 (row 1), and 2014 (row 1). It seems this person is a woman, and her income also increased between the two years. But how do we group this person’s answers together into the same data frame? I discuss this next.</p>
</div>
<div id="joining-data" class="section level1">
<h1>Joining data</h1>
<p>If you’re interested in relational data, you should read Hadley Wickham’s chapter in <a href="http://r4ds.had.co.nz/relational-data.html">R4DS</a> on the topic. He has a great way of explaining the concept and some nice illustrations of exactly what R is doing when joining data.</p>
<p>If we wanted to take <em>all</em> the observations from 2015 and combine them with observations from 2014 (<em>excluding those not relevant to 2015</em>), we would use the left join command. I’ll call this dataframe j1.</p>
<pre class="r"><code>j1 &lt;- y2015 %&gt;%
  left_join(y2014, by = &quot;id&quot;)</code></pre>
<p>The resulting data frame looks like this</p>
<pre class="r"><code>as.tibble(j1)</code></pre>
<pre><code>## # A tibble: 15,118 x 7
##    round.x      id gndr.x income.x round.y gndr.y income.y
##      &lt;int&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;
##  1      24 1000101      2    40000      23      2    36000
##  2      24 1000203      2    47000      23      2    70000
##  3      24 1000301      2    14514      23      2    13180
##  4      24 1000401      2    13400      23      2    12200
##  5      24 1001001      2    22000      23      2    18500
##  6      24 1001102      2    36350      23      2    25000
##  7      24 1001201      2    44000      23      2    45800
##  8      24 1001301      1    28000      23      1    35000
##  9      24 1001302      2    24500      23      2     9300
## 10      24 1001401      2    15300      23      2    10363
## # ... with 15,108 more rows</code></pre>
<p>In total, there are 15,000+ individuals (rows) in the table above, identical to the number of rows in round 24 data above. A number of the observations from 2014 made it in, and a few others did not. For example, in 2014’s data there was a respondent with the number 1000103. Since that respondent didn’t answer the survey in 2015, he never made it into the dataframe above. This frame only contains data from 2015 and the 2014 observations that are relevant to 2015. Note that the variables for gender, round, and income are now split in two. One for 2015 and one for 2014. More on this later.</p>
<p>We can also a do the opposite of above. If we had the 2015 data, we could combine it with data from 2014, giving priority to 2014. In this way, we would take all of 2014 data, and only the 2015 observations that are relevant to 2014. The code below shows this, the data is labeled j2.</p>
<pre class="r"><code>j2 &lt;- y2015 %&gt;%
  right_join(y2014, by = &quot;id&quot;)

as.tibble(j2)</code></pre>
<pre><code>## # A tibble: 15,173 x 7
##    round.x      id gndr.x income.x round.y gndr.y income.y
##      &lt;int&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;
##  1      24 1000101      2    40000      23      2    36000
##  2      NA 1000103     NA       NA      23      1     7240
##  3      24 1000203      2    47000      23      2    70000
##  4      24 1000301      2    14514      23      2    13180
##  5      24 1000401      2    13400      23      2    12200
##  6      24 1001001      2    22000      23      2    18500
##  7      24 1001102      2    36350      23      2    25000
##  8      24 1001201      2    44000      23      2    45800
##  9      24 1001301      1    28000      23      1    35000
## 10      24 1001302      2    24500      23      2     9300
## # ... with 15,163 more rows</code></pre>
<p>In total, there are also, 15,000+ individuals (rows) above, same as in the 2014 data frame shown previously. The outcome is similar to the previous table, respondent number 1000103 is now back, but is missing the observations for 2015, a year where he didn’t take part.</p>
<p>All in all, we could just combine both datasets together. We could say, just lump all observations from both years together, and we will work from there. In this way the frame will hold individuals with values for either year, but not necessarily both years. The data below shows the process.</p>
<pre class="r"><code>j3 &lt;- y2015 %&gt;%
  full_join(y2014, by = &quot;id&quot;)

as.tibble(j3)</code></pre>
<pre><code>## # A tibble: 17,695 x 7
##    round.x      id gndr.x income.x round.y gndr.y income.y
##      &lt;int&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;
##  1      24 1000101      2    40000      23      2    36000
##  2      24 1000203      2    47000      23      2    70000
##  3      24 1000301      2    14514      23      2    13180
##  4      24 1000401      2    13400      23      2    12200
##  5      24 1001001      2    22000      23      2    18500
##  6      24 1001102      2    36350      23      2    25000
##  7      24 1001201      2    44000      23      2    45800
##  8      24 1001301      1    28000      23      1    35000
##  9      24 1001302      2    24500      23      2     9300
## 10      24 1001401      2    15300      23      2    10363
## # ... with 17,685 more rows</code></pre>
<p>There are 17,000+ individuals in the frame above. This frame is larger than the previous ones, since it contains observations from individuals as long as they gave an answer in either year. Finally, we could do the opposite of above, and only focus on those respondents who have an answer in both years. This approach will reduce our data, but will contain a “pure” group of individuals who participated in both years. This is called an inner join, and looks like this.</p>
<pre class="r"><code>j4 &lt;- y2015 %&gt;%
  inner_join(y2014, by = &quot;id&quot;)

as.tibble(j4)</code></pre>
<pre><code>## # A tibble: 12,596 x 7
##    round.x      id gndr.x income.x round.y gndr.y income.y
##      &lt;int&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;   &lt;int&gt;  &lt;int&gt;    &lt;dbl&gt;
##  1      24 1000101      2    40000      23      2    36000
##  2      24 1000203      2    47000      23      2    70000
##  3      24 1000301      2    14514      23      2    13180
##  4      24 1000401      2    13400      23      2    12200
##  5      24 1001001      2    22000      23      2    18500
##  6      24 1001102      2    36350      23      2    25000
##  7      24 1001201      2    44000      23      2    45800
##  8      24 1001301      1    28000      23      1    35000
##  9      24 1001302      2    24500      23      2     9300
## 10      24 1001401      2    15300      23      2    10363
## # ... with 12,586 more rows</code></pre>
<p>This frame is smaller than the previous ones, with 12,000+ individuals (rows) present.</p>
<p>One annoying thing about the tables above, is the split between gender, income and round. There are now two variables for each measure, one for 2014 and one for 2015. Can we combine these?</p>
</div>
<div id="panel" class="section level1">
<h1>Panel</h1>
<p>We can let Rstudio know that the data above is a panel data frame using the <a href="https://cran.r-project.org/web/packages/plm/vignettes/plm.pdf">plm package</a>. Here, we declare the data to be repeated-measured. Before doing this, we have to convert the data from a wide to a long format, we can do this using the reshape package.</p>
<pre class="r"><code>long1&lt;-reshape(j4,
               varying=c(&quot;round.x&quot;,
                         &quot;round.y&quot;,
                         &quot;gndr.x&quot;,
                         &quot;gndr.y&quot;,
                         &quot;income.x&quot;,
                         &quot;income.y&quot;),
               direction=&quot;long&quot;, 
               idvar=&quot;id&quot;,
               sep=&quot;.&quot;)

as.tibble(long1)</code></pre>
<pre><code>## # A tibble: 25,192 x 5
##         id time  round  gndr income
##  *   &lt;int&gt; &lt;chr&gt; &lt;int&gt; &lt;int&gt;  &lt;dbl&gt;
##  1 1000101 x        24     2  40000
##  2 1000203 x        24     2  47000
##  3 1000301 x        24     2  14514
##  4 1000401 x        24     2  13400
##  5 1001001 x        24     2  22000
##  6 1001102 x        24     2  36350
##  7 1001201 x        24     2  44000
##  8 1001301 x        24     1  28000
##  9 1001302 x        24     2  24500
## 10 1001401 x        24     2  15300
## # ... with 25,182 more rows</code></pre>
<p>Finally, we can declare the data to be panel data using the following.</p>
<pre class="r"><code>p1 &lt;- pdata.frame(long1, c(&quot;id&quot;, &quot;round&quot;))
as.tibble(p1)</code></pre>
<pre><code>## # A tibble: 25,192 x 5
##    id      time  round  gndr income
##  * &lt;fct&gt;   &lt;fct&gt; &lt;fct&gt; &lt;int&gt;  &lt;dbl&gt;
##  1 1000101 y     23        2  36000
##  2 1000101 x     24        2  40000
##  3 1000203 y     23        2  70000
##  4 1000203 x     24        2  47000
##  5 1000301 y     23        2  13180
##  6 1000301 x     24        2  14514
##  7 1000401 y     23        2  12200
##  8 1000401 x     24        2  13400
##  9 1001001 y     23        2  18500
## 10 1001001 x     24        2  22000
## # ... with 25,182 more rows</code></pre>
<p>ID now appears twice, for round 23 and round 24. Since we used the inner join data, mentioned earlier, each individual has two observations, from 2014 and from 2015. After some cleaning, we would be able to estimate some interesting things, like the change in income for men and women between rounds.</p>
<p>For now, it is possible to plot some of the panel data by changes in year, using a lag variable.</p>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39;</code></pre>
<p><img src="/post/2018-06-03-adding-observations-in-rlms-using-r_files/figure-html/unnamed-chunk-13-1.png" width="672" /></p>
<p>That’s it for combining observations in RLMS. I hope to move add some more practical posts soon.</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdn.bootcss.com/highlight.js/9.11.0/highlight.min.js"></script>



<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/r.min.js"></script>
<script src="//cdn.bootcss.com/highlight.js/9.11.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    

    
<script>
var doNotTrack = false;
if (!doNotTrack) {
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	ga('create', 'UA-112836068-1', 'auto');
	
	ga('send', 'pageview');
}
</script>

  </body>
</html>

