---
title: A Small Post on Russian Invasion of Ukraine and Subsequent Sanctions
author: Ivan
date: '2022-03-10'
slug: a-small-post-on-russian-invasion-of-ukraine-and-subsequent-sanctions
categories:
  - Blog
tags: []
---


Like everyone I was shocked by the Kremlin's decision to attack Ukraine and the discussion around Ukraine's 'De-Nazification' that has bubbled up in the Kremlin and in parts of Russian society.

Regarding Russia, the war is blatant adventurism and will not achieve any of the Kremlin's goals.
It will create a generation of problems for Russia and its people, and will undo years of economic and social development, not just through sanctions but also through internal stalling of employment and industry. 
Employment will fall, earnings will stall, and the already basic welfare state in Russia will likely be wiped away through a lack of growth.
This will bring a fall in real incomes, an increase in poverty and deprivation, and [a major loss of Human Capital for Russia's workforce](https://www.interfax-russia.ru/main/peskov-riski-rosta-bezraboticy-iz-za-sankciy-byli-proschitany-zaranee). 

Regarding Ukraine, the country will never forgive us for the aggression, neither politically nor culturally. 
If a free Ukraine makes it out of this conflict, it will shun the Russian Federation for a generation on topics of trade, migration and development. 
Migrants who previously contributed to Russian society through work and study, will rightfully boycott the country and native Russians who are more expensive workers at a societal level (since native workers typically consume more resources than migrant workers do) will be left working in poorer positions and conditions, if they can even find work at all.

Although I cannot comment on Ukraine since I don't know anything about the country, I can comment on Russian society and the impact that sanctions and isolation will likely bring. 
In the coming months I hope to offer some baseline estimates of Russia's incomes, poverty, employment and sectoral composition in anticipation of the coming economic shock. 
Already, [we are seeing the impact on society](https://www.interfax-russia.ru/main/peskov-riski-rosta-bezraboticy-iz-za-sankciy-byli-proschitany-zaranee), [with a million people expected to lose work](https://t.me/rian_ru/152260), [the closure of over 250 private sector businesses](https://www.themoscowtimes.com/2022/03/08/250-companies-have-pulled-out-of-russia-since-invasion-a76816), [and the end of freelancing for clients outside of Russia for tens of thousands of people](https://www.themoscowtimes.com/2022/03/10/western-companies-exodus-from-russia-leaves-thousands-of-russians-livelihoods-on-the-line-a76811).

In the coming weeks I hope outline how the labour market looked right before the war broke out, with many data sources being made available up to 2020. 
I also hope to list some of the patterns found by the Levada centre in their analyses of public opinion. 



