baseurl = "/"
languageCode = "en-us"
title = "tupac lives in moscow"
theme = "hugo-lithium-theme"
googleAnalytics = "UA-112836068-1"
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    pre = "fa-bullhorn"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "LinkedIn"
    pre = "fa-linkedin"
    url = "https://www.linkedin.com/in/ivan-privalko-8a790743/"
    weight = 2
[[menu.main]]
    name = "Twitter"
    pre = "fa-twitter"
    url = "https://twitter.com/privlko"
    weight = 3
    

[params]
    


    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"



    [params.logo]
    url = "rladies-r-logo.png"
    width = 50
    height = 50
    alt = "Logo"

