---
title: Some recent reports
author: Ivan
date: '2021-05-24'
slug: some-recent-reports
categories: []
tags:
  - publication
  - paper
  - report
---


Hello! I want to write a quick post about some recent reports and publications that have come out during this year and last year.

My paper on Russian job mobility was published in [Economics of Transition and Institutional Change](https://onlinelibrary.wiley.com/doi/abs/10.1111/ecot.12264)! 
The article looks at gender differences in mobility, before estimating what certain mobility types might mean for wages.
I think there are some gaps in the article that could be addressed in a subsequent paper, like their strong marriage premiums that came up in the results and the strong effects of motherhood. 
I'm leaving this for another for another project though.

We also released a new report on [transfers and deprivation](https://www.esri.ie/publications/social-transfers-and-deprivation-in-ireland-a-study-of-cash-and-non-cash-payments-tied) using Irish data. 
This report looks at housing transfers, medical cards, and imputed values for childcare subsidies. 
We use some new methods to try to estimate the effect these transfers might have on deprivation.
As a spin off, we also wrote a research article which focuses on housing transfers more specifically, with some wider social risk categories.
This is currently under review with a journal.

I also worked briefly on a study on intergenerational inequality in Ireland. 
This was a part of a chapter in the recent [Poverty, income inequality and living standards in Ireland](https://www.esri.ie/publications/poverty-income-inequality-and-living-standards-in-ireland-0). 
In short, the chapter shows that younger workers were disproportionately affected by the COVID-19 economic lock-down.
This is a significant problem for three reasons.
First, young workers are still feeling the impact of the great recession in terms of employment.
Second, their real weekly earnings appear to have fallen relative to other generational groups, and third, they are facing higher housing costs and lower chances of home ownership when compared to previous generations. 
The chapter makes several policy recommendations on how to fix this. 

Lastly, I want to mention a previous work which we are tring to turn into an academic publication. 
In [COVID-19 and non-Irish nationals in Ireland](https://www.esri.ie/publications/covid-19-and-non-irish-nationals-in-ireland) we look at the effect of economic lockdown on different nationality groups in Ireland.
We find that the ability to work from home is a crucial measure for avoiding unemployment, and that it explains several penalties felt by migrants immediately after lockdown was announced by the government. 
This suggests that some of the disadvantage felt by migrants in lockdown can be explained by a type of occupational sorting, where the jobs that migrants do are more important than their status as migrants.
More recently, we have turned the report into a working paper.

These reports and articles are now out, and hopefully some will lead to academic publications.
If you have any suggestions for potential journals or editors please drop me a line on twitter or email.