---
title: 'Real Incomes and Income Growth: Part 3 Income poverty'
author: Ivan Privalko
date: '2022-12-21'
slug: income-poverty-and-equivalised-household-income
categories: []
tags: []
---


The focus so far has been on Russia's income growth over time, with some measures of inequality. 
In this post, I want to look at possible measures of income poverty and how definitions of income poverty, or thresholds of income poverty lead to different rates.
Measures of income poverty are created because policy makers are concerned with a floor in terms of household income, as well as the quality of life that can be achieved for households at such a floor.
An important part of the measure of poverty is deprivation, which is a qualitative measure of what a regaular household can afford. 
Such measures are not available in the RLMS, but other thresholds like falling into a category of being at risk of poerty (60% of median income) are easily calculated using the equivalised household income measure discussed in the previous post. 

# Measures of Income Poverty

Measures of income poverty are relative and related to basic needs. 
However, practically speaking, poverty lines or thresholds are calculated using incomes under which individuals are said to be in or at risk of poverty if crossed.



