---
title: New Papers
author: Ivan
date: '2019-09-16'
slug: new-papers
categories: []
tags:
  - paper
  - uk
  - germany
---


I wanted to include a small update on two recent publications. I know the blog is a bit neglected this is because I've started a postdoc and my first few reports are coming out. [The first is about unpaid work in Ireland and its gender differences.](https://www.esri.ie/publications/caring-and-unpaid-work-in-ireland) I just caught the tail end of the work as I started, but I'm glad I had an input. Generally we find high levels of unpaid work in Ireland when compared to other countries in Europe. 

The second is a peer reviewed paper from my PhD Thesis. In [Quits and Ladders](https://www.emerald.com/insight/content/doi/10.1108/IJM-08-2018-0263/full/html) I compare the effects of quits and promotions on measures of job-fit and on monthly wages. This paper uses panel data from the UK which follows workers over an eight year period.

I also have a working paper which compares the UK and Germany, but I havent found a home for it yet. I am trying to add a section for working papers somewhere on the blog, but I'm not sure what it will look like yet.

I will get back to contributing to the blog over the weeks ahead.

